config/routes.rb
Rails.application.routes.draw do
  resources :hoges
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hoge.rb
class Hoge < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hoges_controller.rb
class HogesController < InheritedResources::Base

  private

    def hoge_params
      params.require(:hoge).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hoges_helper.rb
module HogesHelper
end

app/views/hoges/_form.html.erb
<%= form_for(hoge) do |f| %>
  <% if hoge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hoge.errors.count, "error") %> prohibited this hoge from being saved:</h2>

      <ul>
      <% hoge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hoges/edit.html.erb
<h1>Editing Hoge</h1>

<%= render 'form', hoge: @hoge %>

<%= link_to 'Show', @hoge %> |
<%= link_to 'Back', hoges_path %>

app/views/hoges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hoges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hoges.each do |hoge| %>
      <tr>
        <td><%= hoge.name %></td>
        <td><%= hoge.age %></td>
        <td><%= link_to 'Show', hoge %></td>
        <td><%= link_to 'Edit', edit_hoge_path(hoge) %></td>
        <td><%= link_to 'Destroy', hoge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hoge', new_hoge_path %>

app/views/hoges/new.html.erb
<h1>New Hoge</h1>

<%= render 'form', hoge: @hoge %>

<%= link_to 'Back', hoges_path %>

app/views/hoges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hoge.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @hoge.age %>
</p>

<%= link_to 'Edit', edit_hoge_path(@hoge) %> |
<%= link_to 'Back', hoges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>